---
- name: Update and install jdk and net tools
  hosts: webserver
    become: yes
    become_user: root
    tasks:
      - name: Update apt repo and cache
        apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
      - name: Install Java dk 11
        apt: name=openjdk-11-jre-headless
      - name: Install net-tools
        apt: name=net-tools
